import type { Metadata } from "next";
import "./globals.css";
import "animate.css"; // <-- import จาก node_modules
import LoginPage from "./admin/login/page";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        {children}
        <LoginPage />
      </body>
    </html>
  );
}
